/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BudgetRange = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type BusinessType = { 'enterprise' : null } |
  { 'startup' : null } |
  { 'nonProfit' : null } |
  { 'smallBusiness' : null } |
  { 'individual' : null };
export interface Contact {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface ContactMessage {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type DesignStyle = { 'classic' : null } |
  { 'playful' : null } |
  { 'professional' : null } |
  { 'minimalist' : null } |
  { 'modern' : null };
export interface Project {
  'id' : string,
  'serviceType' : ServiceType,
  'country' : string,
  'featuresRequired' : Array<string>,
  'serviceDetails' : Array<ServiceDetail>,
  'owner' : Principal,
  'designStyle' : DesignStyle,
  'name' : string,
  'businessName' : string,
  'businessType' : BusinessType,
  'email' : string,
  'timestamp' : Time,
  'budgetRange' : BudgetRange,
}
export interface ProjectRequest {
  'id' : string,
  'serviceType' : ServiceType,
  'country' : string,
  'featuresRequired' : Array<string>,
  'serviceDetails' : Array<ServiceDetail>,
  'owner' : Principal,
  'designStyle' : DesignStyle,
  'name' : string,
  'businessName' : string,
  'businessType' : BusinessType,
  'email' : string,
  'timestamp' : Time,
  'budgetRange' : BudgetRange,
}
export type ServiceDetail = { 'enum' : string } |
  { 'name' : string };
export type ServiceType = { 'graphicDesign' : null } |
  { 'other' : null } |
  { 'consulting' : null } |
  { 'webDevelopment' : null } |
  { 'branding' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllContactMessages' : ActorMethod<[], Array<Contact>>,
  'getAllProjectRequests' : ActorMethod<[], Array<Project>>,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'submitProjectRequest' : ActorMethod<[ProjectRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];