/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Contact = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ServiceType = IDL.Variant({
  'graphicDesign' : IDL.Null,
  'other' : IDL.Null,
  'consulting' : IDL.Null,
  'webDevelopment' : IDL.Null,
  'branding' : IDL.Null,
});
export const ServiceDetail = IDL.Variant({
  'enum' : IDL.Text,
  'name' : IDL.Text,
});
export const DesignStyle = IDL.Variant({
  'classic' : IDL.Null,
  'playful' : IDL.Null,
  'professional' : IDL.Null,
  'minimalist' : IDL.Null,
  'modern' : IDL.Null,
});
export const BusinessType = IDL.Variant({
  'enterprise' : IDL.Null,
  'startup' : IDL.Null,
  'nonProfit' : IDL.Null,
  'smallBusiness' : IDL.Null,
  'individual' : IDL.Null,
});
export const BudgetRange = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'serviceType' : ServiceType,
  'country' : IDL.Text,
  'featuresRequired' : IDL.Vec(IDL.Text),
  'serviceDetails' : IDL.Vec(ServiceDetail),
  'owner' : IDL.Principal,
  'designStyle' : DesignStyle,
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'businessType' : BusinessType,
  'email' : IDL.Text,
  'timestamp' : Time,
  'budgetRange' : BudgetRange,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ProjectRequest = IDL.Record({
  'id' : IDL.Text,
  'serviceType' : ServiceType,
  'country' : IDL.Text,
  'featuresRequired' : IDL.Vec(IDL.Text),
  'serviceDetails' : IDL.Vec(ServiceDetail),
  'owner' : IDL.Principal,
  'designStyle' : DesignStyle,
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'businessType' : BusinessType,
  'email' : IDL.Text,
  'timestamp' : Time,
  'budgetRange' : BudgetRange,
});

export const idlService = IDL.Service({
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllProjectRequests' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'submitProjectRequest' : IDL.Func([ProjectRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ServiceType = IDL.Variant({
    'graphicDesign' : IDL.Null,
    'other' : IDL.Null,
    'consulting' : IDL.Null,
    'webDevelopment' : IDL.Null,
    'branding' : IDL.Null,
  });
  const ServiceDetail = IDL.Variant({ 'enum' : IDL.Text, 'name' : IDL.Text });
  const DesignStyle = IDL.Variant({
    'classic' : IDL.Null,
    'playful' : IDL.Null,
    'professional' : IDL.Null,
    'minimalist' : IDL.Null,
    'modern' : IDL.Null,
  });
  const BusinessType = IDL.Variant({
    'enterprise' : IDL.Null,
    'startup' : IDL.Null,
    'nonProfit' : IDL.Null,
    'smallBusiness' : IDL.Null,
    'individual' : IDL.Null,
  });
  const BudgetRange = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'serviceType' : ServiceType,
    'country' : IDL.Text,
    'featuresRequired' : IDL.Vec(IDL.Text),
    'serviceDetails' : IDL.Vec(ServiceDetail),
    'owner' : IDL.Principal,
    'designStyle' : DesignStyle,
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'businessType' : BusinessType,
    'email' : IDL.Text,
    'timestamp' : Time,
    'budgetRange' : BudgetRange,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ProjectRequest = IDL.Record({
    'id' : IDL.Text,
    'serviceType' : ServiceType,
    'country' : IDL.Text,
    'featuresRequired' : IDL.Vec(IDL.Text),
    'serviceDetails' : IDL.Vec(ServiceDetail),
    'owner' : IDL.Principal,
    'designStyle' : DesignStyle,
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'businessType' : BusinessType,
    'email' : IDL.Text,
    'timestamp' : Time,
    'budgetRange' : BudgetRange,
  });
  
  return IDL.Service({
    'getAllContactMessages' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllProjectRequests' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'submitProjectRequest' : IDL.Func([ProjectRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };