/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactMessage {
    id: string;
    owner: Principal;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export type Time = bigint;
export interface Contact {
    id: string;
    owner: Principal;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export type ServiceDetail = {
    __kind__: "enum";
    enum: string;
} | {
    __kind__: "name";
    name: string;
};
export interface Project {
    id: string;
    serviceType: ServiceType;
    country: string;
    featuresRequired: Array<string>;
    serviceDetails: Array<ServiceDetail>;
    owner: Principal;
    designStyle: DesignStyle;
    name: string;
    businessName: string;
    businessType: BusinessType;
    email: string;
    timestamp: Time;
    budgetRange: BudgetRange;
}
export interface ProjectRequest {
    id: string;
    serviceType: ServiceType;
    country: string;
    featuresRequired: Array<string>;
    serviceDetails: Array<ServiceDetail>;
    owner: Principal;
    designStyle: DesignStyle;
    name: string;
    businessName: string;
    businessType: BusinessType;
    email: string;
    timestamp: Time;
    budgetRange: BudgetRange;
}
export enum BudgetRange {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum BusinessType {
    enterprise = "enterprise",
    startup = "startup",
    nonProfit = "nonProfit",
    smallBusiness = "smallBusiness",
    individual = "individual"
}
export enum DesignStyle {
    classic = "classic",
    playful = "playful",
    professional = "professional",
    minimalist = "minimalist",
    modern = "modern"
}
export enum ServiceType {
    graphicDesign = "graphicDesign",
    other = "other",
    consulting = "consulting",
    webDevelopment = "webDevelopment",
    branding = "branding"
}
export interface backendInterface {
    getAllContactMessages(): Promise<Array<Contact>>;
    getAllProjectRequests(): Promise<Array<Project>>;
    submitContactMessage(message: ContactMessage): Promise<void>;
    submitProjectRequest(request: ProjectRequest): Promise<void>;
}
import type { BudgetRange as _BudgetRange, BusinessType as _BusinessType, DesignStyle as _DesignStyle, Project as _Project, ProjectRequest as _ProjectRequest, ServiceDetail as _ServiceDetail, ServiceType as _ServiceType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllContactMessages(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactMessages();
            return result;
        }
    }
    async getAllProjectRequests(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjectRequests();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjectRequests();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactMessage(arg0: ContactMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0);
            return result;
        }
    }
    async submitProjectRequest(arg0: ProjectRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProjectRequest(to_candid_ProjectRequest_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProjectRequest(to_candid_ProjectRequest_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BudgetRange_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetRange): BudgetRange {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_BusinessType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessType): BusinessType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_DesignStyle_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignStyle): DesignStyle {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceDetail_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceDetail): ServiceDetail {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    serviceType: _ServiceType;
    country: string;
    featuresRequired: Array<string>;
    serviceDetails: Array<_ServiceDetail>;
    owner: Principal;
    designStyle: _DesignStyle;
    name: string;
    businessName: string;
    businessType: _BusinessType;
    email: string;
    timestamp: _Time;
    budgetRange: _BudgetRange;
}): {
    id: string;
    serviceType: ServiceType;
    country: string;
    featuresRequired: Array<string>;
    serviceDetails: Array<ServiceDetail>;
    owner: Principal;
    designStyle: DesignStyle;
    name: string;
    businessName: string;
    businessType: BusinessType;
    email: string;
    timestamp: Time;
    budgetRange: BudgetRange;
} {
    return {
        id: value.id,
        serviceType: from_candid_ServiceType_n4(_uploadFile, _downloadFile, value.serviceType),
        country: value.country,
        featuresRequired: value.featuresRequired,
        serviceDetails: from_candid_vec_n6(_uploadFile, _downloadFile, value.serviceDetails),
        owner: value.owner,
        designStyle: from_candid_DesignStyle_n9(_uploadFile, _downloadFile, value.designStyle),
        name: value.name,
        businessName: value.businessName,
        businessType: from_candid_BusinessType_n11(_uploadFile, _downloadFile, value.businessType),
        email: value.email,
        timestamp: value.timestamp,
        budgetRange: from_candid_BudgetRange_n13(_uploadFile, _downloadFile, value.budgetRange)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    classic: null;
} | {
    playful: null;
} | {
    professional: null;
} | {
    minimalist: null;
} | {
    modern: null;
}): DesignStyle {
    return "classic" in value ? DesignStyle.classic : "playful" in value ? DesignStyle.playful : "professional" in value ? DesignStyle.professional : "minimalist" in value ? DesignStyle.minimalist : "modern" in value ? DesignStyle.modern : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    enterprise: null;
} | {
    startup: null;
} | {
    nonProfit: null;
} | {
    smallBusiness: null;
} | {
    individual: null;
}): BusinessType {
    return "enterprise" in value ? BusinessType.enterprise : "startup" in value ? BusinessType.startup : "nonProfit" in value ? BusinessType.nonProfit : "smallBusiness" in value ? BusinessType.smallBusiness : "individual" in value ? BusinessType.individual : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): BudgetRange {
    return "low" in value ? BudgetRange.low : "high" in value ? BudgetRange.high : "medium" in value ? BudgetRange.medium : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    graphicDesign: null;
} | {
    other: null;
} | {
    consulting: null;
} | {
    webDevelopment: null;
} | {
    branding: null;
}): ServiceType {
    return "graphicDesign" in value ? ServiceType.graphicDesign : "other" in value ? ServiceType.other : "consulting" in value ? ServiceType.consulting : "webDevelopment" in value ? ServiceType.webDevelopment : "branding" in value ? ServiceType.branding : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    enum: string;
} | {
    name: string;
}): {
    __kind__: "enum";
    enum: string;
} | {
    __kind__: "name";
    name: string;
} {
    return "enum" in value ? {
        __kind__: "enum",
        enum: value.enum
    } : "name" in value ? {
        __kind__: "name",
        name: value.name
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceDetail>): Array<ServiceDetail> {
    return value.map((x)=>from_candid_ServiceDetail_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BudgetRange_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetRange): _BudgetRange {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_BusinessType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): _BusinessType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_DesignStyle_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignStyle): _DesignStyle {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectRequest): _ProjectRequest {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceDetail_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceDetail): _ServiceDetail {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    serviceType: ServiceType;
    country: string;
    featuresRequired: Array<string>;
    serviceDetails: Array<ServiceDetail>;
    owner: Principal;
    designStyle: DesignStyle;
    name: string;
    businessName: string;
    businessType: BusinessType;
    email: string;
    timestamp: Time;
    budgetRange: BudgetRange;
}): {
    id: string;
    serviceType: _ServiceType;
    country: string;
    featuresRequired: Array<string>;
    serviceDetails: Array<_ServiceDetail>;
    owner: Principal;
    designStyle: _DesignStyle;
    name: string;
    businessName: string;
    businessType: _BusinessType;
    email: string;
    timestamp: _Time;
    budgetRange: _BudgetRange;
} {
    return {
        id: value.id,
        serviceType: to_candid_ServiceType_n17(_uploadFile, _downloadFile, value.serviceType),
        country: value.country,
        featuresRequired: value.featuresRequired,
        serviceDetails: to_candid_vec_n19(_uploadFile, _downloadFile, value.serviceDetails),
        owner: value.owner,
        designStyle: to_candid_DesignStyle_n22(_uploadFile, _downloadFile, value.designStyle),
        name: value.name,
        businessName: value.businessName,
        businessType: to_candid_BusinessType_n24(_uploadFile, _downloadFile, value.businessType),
        email: value.email,
        timestamp: value.timestamp,
        budgetRange: to_candid_BudgetRange_n26(_uploadFile, _downloadFile, value.budgetRange)
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    graphicDesign: null;
} | {
    other: null;
} | {
    consulting: null;
} | {
    webDevelopment: null;
} | {
    branding: null;
} {
    return value == ServiceType.graphicDesign ? {
        graphicDesign: null
    } : value == ServiceType.other ? {
        other: null
    } : value == ServiceType.consulting ? {
        consulting: null
    } : value == ServiceType.webDevelopment ? {
        webDevelopment: null
    } : value == ServiceType.branding ? {
        branding: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "enum";
    enum: string;
} | {
    __kind__: "name";
    name: string;
}): {
    enum: string;
} | {
    name: string;
} {
    return value.__kind__ === "enum" ? {
        enum: value.enum
    } : value.__kind__ === "name" ? {
        name: value.name
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignStyle): {
    classic: null;
} | {
    playful: null;
} | {
    professional: null;
} | {
    minimalist: null;
} | {
    modern: null;
} {
    return value == DesignStyle.classic ? {
        classic: null
    } : value == DesignStyle.playful ? {
        playful: null
    } : value == DesignStyle.professional ? {
        professional: null
    } : value == DesignStyle.minimalist ? {
        minimalist: null
    } : value == DesignStyle.modern ? {
        modern: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): {
    enterprise: null;
} | {
    startup: null;
} | {
    nonProfit: null;
} | {
    smallBusiness: null;
} | {
    individual: null;
} {
    return value == BusinessType.enterprise ? {
        enterprise: null
    } : value == BusinessType.startup ? {
        startup: null
    } : value == BusinessType.nonProfit ? {
        nonProfit: null
    } : value == BusinessType.smallBusiness ? {
        smallBusiness: null
    } : value == BusinessType.individual ? {
        individual: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetRange): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == BudgetRange.low ? {
        low: null
    } : value == BudgetRange.high ? {
        high: null
    } : value == BudgetRange.medium ? {
        medium: null
    } : value;
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ServiceDetail>): Array<_ServiceDetail> {
    return value.map((x)=>to_candid_ServiceDetail_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
